version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: bvv-dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"  # You can access pgAdmin at http://localhost:5050
    depends_on:
      - postgres

volumes:
  pg_data:
  pgadmin_data: