version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bvv-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      # Environment variables for the NestJS backend to connect to Postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: "5432"
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: bvv-test
    depends_on:
      - postgres
    ports:
      - "3001:3000"  # Adjust port mapping as needed

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - backend  # Optional: if your web app requires the backend during startup
    ports:
      - "3000:3000"  # Adjust port mapping as needed

volumes:
  postgres_data:
