
name: PR Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  pr-checks-and-build:
    name: Lint & Formatting Checks then Build Application and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and turbo
        run: npm install -g pnpm turbo

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier Check
        run: turbo format:check

      - name: Run ESLint Check
        run: turbo lint

      - name: Build
        run: turbo build

      - name: Run Tests
        run: turbo test
