
name: PR Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  pr-checks-and-build:
    name: Lint & Formatting Checks then Build Application and Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment with version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install turbo
        run: npm install -g turbo

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier Check
        run: turbo format:check

      - name: Run ESLint Check
        run: turbo lint

      - name: Build
        run: turbo build

      - name: Run Tests
        run: turbo test